/* 
    this file will test some functions, the functions in these files:
    "accessStringArrayByRowAndCol.c"
    "sumIntArray.c"
    "countNOccurrencesOfARowString.c"
    the expected is the code generated by this script print the number 2.
    the objective of this test is to search how much times the row in the given
    "uniques" variable happens in the "dt" variable, the row
    happens two times. so the expected is this function print 2.
*/

#include <stdio.h>
#include <string.h>
#include "../include/myself/countNOccurrencesOfARowString.c"

int main(){
    char *dt[9]={"foo", "ead", "foo", "chip", "fsd", "chip", "bar", "cwerhip", "bar"};
    char *uniques[3]={"foo", "chip", "bar"};
    int occurrences=countNOccurrencesOfARowString(uniques, dt, 3, 3);
    printf("%i", occurrences);
    return 0;
}

