# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Rcpp_pdf_normal
#' @description normal distribution PDF from: "https://web.stanford.edu/class/archive/cs/cs109/cs109.1178/lectureHandouts/110-normal-distribution.pdf".
#' @param x the target probability
#' @param mean the mean of the distribution
#' @param stddev the standard deviation
#' @return a double with PDF
#' @export
pdf_normal <- function(x, mean, stddev) {
    .Call('_monteCarloR_pdf_normal', PACKAGE = 'monteCarloR', x, mean, stddev)
}

